### PR TITLE
`state` added to appRule.

### LINKED ISSUE #131: Allow a fullscreen attribute in appRules
At the request of @PMunch

### PR DESCRIPTION
**Pull request by avahe-kellenberger**
Closes #131

In an `appRule`, a `state` for the window can be set.

```toml
[[appRule]]
class = "xlunch-windowed"
state = "fullscreen" # "normal", "floating", and "fullscreen" are all valid.
```

@PMunch If you want to test this build (since I did this PR per your request), let me know how it goes.
I'll do more manual testing this week.

@dakyskye  as well

### CODE REVIEW

**Comment by dakyskye** [comment]
Does not work for me with this settings:
```toml
[[appRule]]
class = "kitty"
title="htop"
state = "floating"
```
xprop output:
```
WM_NAME(STRING) = "htop"
WM_CLASS(STRING) = "kitty", "kitty"
```

**Comment by dakyskye** [comment]
Oh, it does not work when `title` is used. Just removed it and it's fine (though, it didn't draw border and the default window size isn't good either)
image

**Comment by avahe-kellenberger** [comment]
@dakyskye I've made a lot of changes if you care to try this out again.

**Comment by dakyskye** [comment]
I've tried it. I launched `kitty zsh` which sets `zsh` as title and it didn't work. Then I commented out `title` key and it worked (made kitty window floating and toggled it on three tags).

**Comment by avahe-kellenberger** [comment]
Kitty probably sets the title late (after the window is mapped) I assume, the title param works for me in every application

**Pull request merged**
