### PR TITLE
Clicking a tag no longer warps the cursor to the current client.

### PR DESCRIPTION
**Pull request by avahe-kellenberger**
- Minor code cleanup

@PMunch requesting your review of functionality, should be quick. Just want to make sure there wasn't a regression from your PR

### CODE REVIEW

**Review by PMunch — APPROVED** [review]
Looks good to me. Works fine as well. Only thing I noticed was that if one of my click events triggers a window to open (I have things in my status bar that opens `htop`, `pavucontrol`, firefox tabs, and other things) then the cursor will be centred on those windows. Not sure if this also applies to floating windows, haven't tried that yet, but could potentially be annoying if you set up a volume slider window for example.

**Comment by avahe-kellenberger** [comment]
Good catch, thanks. I'll fix that soon.

**Comment by avahe-kellenberger** [comment]
@PMunch I've fixed the issue for floating windows (not sure if we should not jump to tiled windows, thoughts?)

Tested it by adding the following to the config:

```toml
[[appRule]]
class = "pavucontrol-clicked"
state = "floating"

[[startProcess]]
clickRegion = 1
command = "pavucontrol --class=\"pavucontrol-clicked\""
```

**Comment by PMunch** [comment]
Hmm, I don't have any of my windows set up to float, so I noticed the issue with non-floating windows. It's hard to make this work properly, because knowing when a window was created by the mouse is tricky. One option that at least would be deterministic is to never move the mouse if you have clicked the bar and haven't left it yet. So if you accidentally move the mouse onto the bar it won't have an effect, but from the time you click something on the bar until you move it out or perform a keyboard shortcut it won't  move. If you manage to move the mouse away from the bar before the window appears the mouse would still jump, but I feel like that is a small edge case.

But to expand on this the reason the mouse is moved when a window appears I assume is for focusing reasons. I feel like you could track two "input modes" that would make it feel more natural. Based on the last action you're either in "mouse mode" or "keyboard mode". If you have moved the mouse or clicked anything you're in "mouse mode" and if you have triggered a keyboard shortcut you're in "keyboard mode". This would mean that if I spawn the menu to spawn a program through a keyboard shortcut the mouse would move there. But if I'm moving the mouse around and a window appears for some reason (looking at you Steam, with you're horribly delayed window creation), then the mouse won't suddenly jump out from under you. I think that this would feel very natural, and would solve this issue as well (which is an issue of what feels natural or not). I actually implemented a small thing when I was using i3 that allowed me to do Super+Mouse button to spawn a small circular menu under the mouse that would allow me to run different things. This would feel awkward if the mouse moved around, so if you ever implement keyboard+mouse button shortcuts I think those should count as "mouse mode".

**Comment by avahe-kellenberger** [comment]
I really like the idea of the mouse vs. keyboard modes.

I'll take a stab at the implementation.

**Pull request merged**
