### PR TITLE
Add scratchpad

### PR DESCRIPTION
**Pull request by uninhm**
I'm not sure if that's exactly how "scratchpad" should work, but it's an advance.

### CODE REVIEW

**Comment by uninhm** [comment]
#133

**Comment by uninhm** [comment]
https://github.com/avahe-kellenberger/nimdow/pull/150/commits/2b1a64ce24326881dabcf0fdae2a39f6fbac944a

Using for loop isn't beauty, if you know how to do it better please let me know

**Comment by avahe-kellenberger** [comment]
Been out the past few days but I'll be checking your PRs and issues this week. Thanks for contributing!

**Comment by uninhm** [comment]
Should I create `scratchpad.nim` file, with a `Scratchpad` type and some procs like `popFirstClient`, `popLastClient` and `addClient`?

**Comment by avahe-kellenberger** [comment]
That sounds like a good idea, just wrapping some procs from dequeue

**Comment by avahe-kellenberger** [comment]
I'm not sure about the desired behavior either (never used a scratchpad) but it does seem odd to me that a non-floating window becomes floating.

@dakyskye Could you chime in with your experience here, and/or opinions on the matter?

**Comment by uninhm** [comment]
Sorry for the double commit, I thought I hadn't committed yet

**Comment by dakyskye** [comment]
As I see you save the geometry of a window before throwing it to the scratchpad but that causes some issues later on (for example, if you scratchpaded the only window in a tag, then opened a master and a couple of slave windows and retained the scratchpaded window, it'd spawn on top of all of them).

I think you should only save the state of a window, not the geometry.

**Comment by uninhm** [comment]
Ok, so...
1) If window is tiled, recover resized in the center
2) If window is floating, recover as it was before pushing to scratchpad

**Comment by avahe-kellenberger** [comment]
@uninhm Still plan on getting this PR merged? I can assist with any issues you may have

**Comment by uninhm** [comment]
I think it's ready

**Review by avahe-kellenberger — APPROVED** [review]
Looks good. I'll merge, going to do a slight rename from `popScratchpadLast` to `popScratchpad` and update the man page.

Thanks again for contributing!

**Pull request merged**
