### PR TITLE
Custom tag text

### PR DESCRIPTION
**Pull request by avahe-kellenberger**
Needs to be tested and have a written section in the wiki.

### CODE REVIEW

**Comment by dakyskye** [comment]
hey @avahe-kellenberger glad to see some progress. hit me up if you need me to test stuff

**Comment by avahe-kellenberger** [comment]
Last issue to resolve, is providing a `MontiorSettings` object for all monitors, even if there is no info for a monitor in the new config. Will go into more testing afterward (will probably finish this tomorrow).

**Comment by avahe-kellenberger** [comment]
@dakyskye This branch is ready for testing.

I've added the config block "monitors" - you can see an example in `config.default.toml`. This will allow you to change the displayed text for tags on the fly (should work with config reloading).

If you have questions, hit me up on Matrix or comment here. Thanks for testing!

**Comment by avahe-kellenberger** [comment]
I need to change the urgent bg color - it's currently being rendered on top of the tag text.

**Comment by dakyskye** [comment]
Sorry, didn't have time to test the changes. Also, I now have single monitor setup. I'll test this branch when I get free time if it won't be merged already.

**Comment by avahe-kellenberger** [comment]
Another thing to fix: window title rendering can render over the status bar. This probably means the return value of `renderTags` is now incorrect.

**Comment by dakyskye** [comment]
> Another thing to fix: window title rendering can render over the status bar. This probably means the return value of `renderTags` is now incorrect.

can it? my status text is always over my title text

**Comment by avahe-kellenberger** [comment]
I saw it happening on this specific branch, but I've been unable to replicate it. Going to try again soon, if I can't replicate the issue I'll just merge this in.

**Comment by avahe-kellenberger** [comment]
Resolved. Time to test config options, and start writing the wiki changes.

**Comment by avahe-kellenberger** [comment]
@dakyskye If you can test this branch, plz let me know if you notice anything strange with the status or title text. I saw a bug, but have been unable to replicate it.

**Pull request merged**
