### PR TITLE
Command line client

### LINKED ISSUE #72: Command line client
Just like i3 wm has i3-msg, bspwm has bspc, qtile has qtile-cmd, herbstluftwm has herbsclient etc. Nimdow should also have a cmdline client, that will allow users to do everything Nimdow can with it.

### PR DESCRIPTION
**Pull request by avahe-kellenberger**
Resolves #72 

@dakyskye If you want to test this out before I do a release. I plan on doing more work before merging.

## Changes

Nimdow now uses a Unix socket for IPC. It currently only accepts a connect for one command to be sent, then closes the connection.

This means you can send single commands via the `nimdow` executable (one at a time).

**The syntax is flexible.**

### Examples
- `nimdow --go-to-tag 3` will take you to tag 3
- `nimdow focusPrevious` will focus the previously selected window

## Notes
Socket location: `$XDG_RUNTIME_DIR/nimdow/ipc-socket.%p` where %p is the PID of nimdow.

### CODE REVIEW

**Comment by avahe-kellenberger** [comment]
Full dxhd config to replace the `config` table in `nimdow.conf`:

```sh
#!/usr/bin/env bash

# super + shift + r
  nimdow --reload-config

# super + k
  nimdow --focus-previous

# super + j
  nimdow --focus-next

# super + shift + k
  nimdow --move-window-previous

# super + shift + j
  nimdow --move-window-next

# super + f
  nimdow --toggle-fullscreen

# super + shift + q
  nimdow --destroy-selected-window

# super + {1-9}
  nimdow --go-to-tag {1-9}

# super + w
  nimdow --go-to-previous-tag

# super + shift + {1-9}
  nimdow --move-window-to-tag {1-9}

# super + shift + w
  nimdow --move-window-to-previous-tag

# super + control + {1-9}
  nimdow --toggle-tag-view {1-9}

# super + shift + control + {1-9}
  nimdow --toggle-window-tag {1-9}

# super + comma
  nimdow --focus-previous-monitor

# super + period
  nimdow --focus-next-monitor

# super + shift + comma
  nimdow --move-window-to-previous-monitor

# super + shift + period
  nimdow --move-window-to-next-monitor

# super + z
  nimdow --increase-master-count

# super + x
  nimdow --decrease-master-count

# super + space
  nimdow --toggle-floating

# super + u
  nimdow --jump-to-urgent-window
```

**Comment by dakyskye** [comment]
@avahe-kellenberger that's sweet :heart: however dxhd is more scripting friendly, does not need extra indention at the beginning of  a command.

**Comment by dakyskye** [comment]
I am gonna build the CLI branch and test it :+1:

**Comment by dakyskye** [comment]
I get this error when I try to use any flag.
```
nimdow --go-to-tag 2
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  7
  Current serial number in output stream:  8
```

**Comment by avahe-kellenberger** [comment]
Must be the old executable, not the one you built (unless you built a different branch?)

**Comment by dakyskye** [comment]
Oh :joy: yeah I built the master branch, my bad. Okay, will give it a go tomorrow.

**Comment by dakyskye** [comment]
Works great :100:

**Comment by avahe-kellenberger** [comment]
Awesome! I'll merge and deploy today

**Comment by dakyskye** [comment]
Make sure to add `--help` flag which will list the commands or at least point to github wiki.

**Comment by avahe-kellenberger** [comment]
Good idea

**Comment by avahe-kellenberger** [comment]
@dakyskye Released :rocket: The AUR package will install the man page.

**Comment by dakyskye** [comment]
@avahe-kellenberger I love that man page!

**Pull request merged**
